### ISSUE TITLE
v2.2.1 Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by bgavas** [TheAppleFreak/winston-slack-webhook-transport#21]
I am using `"winston": "^3.3.3"` and `"winston-slack-webhook-transport": "^2.1.0"`. After your version update today, I had to fix the version to `"2.1.0".` Otherwise I am getting `Cannot read properties of undefined (reading 'create')` on `PRODUCTION` which is really annoying.

```
TypeError: Cannot read properties of undefined (reading 'create')
    at new SlackHook (/Users/my-path/node_modules/winston-slack-webhook-transport/slackHook.js:24:32)
    at Object.<anonymous> (/Users/my-path/src/utils/helpers/logger.helper.ts:78:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/my-path/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/my-path/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by TheAppleFreak** [comment]
Thanks for letting me know about this! Giving it a look now.

**Comment by bgavas** [comment]
> Thanks for letting me know about this! Giving it a look now.

I am using `"axios": "^0.21.1"` in my project. The reason may be the change in axios' version where you upgraded to `1.0.0`

**Comment by TheAppleFreak** [comment]
Yeah, that's my guess too. I'm reading over the axios changelog and documentation right now to see if the API changed, but it doesn't appear as if my code is doing anything wrong. Figure it's probably best to roll back to a known good axios release for the time being. 

I'll get that change made and pushed in a few minutes. Sorry about the issues!

**Comment by bgavas** [comment]
Thanks for your quick help. Cheers

**Comment by TheAppleFreak** [comment]
Alright, v2.2.2 has been published! It reverts the axios version change. Can you try that version and confirm if it's working for you?

**Comment by bgavas** [comment]
Yeah, I tested it and it is working. Thanks!

**Comment by TheAppleFreak** [comment]
Excellent! Again, thank you for letting me know about this.
